### ISSUE TITLE
unable to start self-hosted

### ISSUE THREAD

**Issue by jadewolf05** [BattlefieldDuck/DiscordGSM#30]
I installed the DiscordGSM docker container on my unraid server using the comunity apps.

I have the config setup, but when I start the container, it quickly goes into "stopped" state again with the following in the logs:
usermod: no changes
usermod: no changes
Server Config found!
Settings Config found!

Any ideas on why it won't start?  Let me know what additional info may be needed for this.

**Comment by jadewolf05** [comment]
after a full restart of the docker, I see this in the logs:
Traceback (most recent call last):
  File "/dgsm-docker/bot.py", line 29, in <module>
    clientid = base64.b64decode(segs[0]).decode()
  File "/usr/local/lib/python3.10/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
Server Config found!
Settings Config found!
usermod: no changes
usermod: no changes
Server Config found!
Settings Config found!

**Comment by xLeviNx** [comment]
Edit the following in bot.py

Remove 
>clientid = base64.b64decode(segs[0]).decode()

and then add

>mybytes = b'=='
tokn = segs[0] + mybytes.decode('utf-8')
clientid = base64.b64decode(tokn).decode()

**Comment by Vibeshibe** [comment]
Also experiencing this issue. I got a already running bot and trying to run a seperate branded one for a friend's where it runs into this issue despite having the same docker image.

**Comment by jadewolf05** [comment]
after making the above change and restarting, this is what I get now.

Traceback (most recent call last):
  File "/dgsm-docker/bot.py", line 456, in <module>
    discordgsm = DiscordGSM(client)
  File "/dgsm-docker/bot.py", line 66, in __init__
    self.servers = Servers()
  File "/dgsm-docker/servers.py", line 14, in __init__
    self.refresh()
  File "/dgsm-docker/servers.py", line 18, in refresh
    servers = self.get()
  File "/dgsm-docker/servers.py", line 49, in get
    return json.loads(data)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 9 column 5 (char 234)
Traceback (most recent call last):
  File "/dgsm-docker/bot.py", line 456, in <module>
    discordgsm = DiscordGSM(client)
  File "/dgsm-docker/bot.py", line 66, in __init__
    self.servers = Servers()
  File "/dgsm-docker/servers.py", line 14, in __init__
    self.refresh()
  File "/dgsm-docker/servers.py", line 18, in refresh
    servers = self.get()
  File "/dgsm-docker/servers.py", line 49, in get
    return json.loads(data)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 9 column 5 (char 234)
Server Config found!
Settings Config found!
usermod: no changes
usermod: no changes
Server Config found!
Settings Config found!


a find on the bot.py file produced several locations.  I ended up making the change on all the following:
/var/lib/docker/btrfs/subvolumes/1784ad43d48d350fba43a1e3422a6da072e29c367c61b5ee46811ab459b31c3b/dgsm-docker/bot.py
/var/lib/docker/btrfs/subvolumes/321a826569eed6449722cd515846c3ff9b7862c64829f8bdb1907d7d5a361345/dgsm-docker/bot.py
/var/lib/docker/btrfs/subvolumes/4bebe5b47999f96791d7b43fe442df77ff83ecd9b8cf8abc38b7d2f5e9fbecfd-init/dgsm-docker/bot.py
/var/lib/docker/btrfs/subvolumes/4bebe5b47999f96791d7b43fe442df77ff83ecd9b8cf8abc38b7d2f5e9fbecfd/dgsm-docker/bot.py
/var/lib/docker/btrfs/subvolumes/5ca820afe73afdb97125117ba4f1c8764ef2c02a236d956dd5d6851836831d3d/dgsm-docker/bot.py

**Comment by jadewolf05** [comment]
for refernce, this is the change:

![image](https://user-images.githubusercontent.com/33162939/185629524-d88afc96-4332-4771-aa41-11715d0c263a.png)

**Comment by xLeviNx** [comment]
> after making the above change and restarting, this is what I get now.
> 
> Traceback (most recent call last): File "/dgsm-docker/bot.py", line 456, in discordgsm = DiscordGSM(client) File "/dgsm-docker/bot.py", line 66, in **init** self.servers = Servers() File "/dgsm-docker/servers.py", line 14, in **init** self.refresh() File "/dgsm-docker/servers.py", line 18, in refresh servers = self.get() File "/dgsm-docker/servers.py", line 49, in get return json.loads(data) File "/usr/local/lib/python3.10/json/**init**.py", line 346, in loads return _default_decoder.decode(s) File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode obj, end = self.scan_once(s, idx) json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 9 column 5 (char 234) Traceback (most recent call last): File "/dgsm-docker/bot.py", line 456, in discordgsm = DiscordGSM(client) File "/dgsm-docker/bot.py", line 66, in **init** self.servers = Servers() File "/dgsm-docker/servers.py", line 14, in **init** self.refresh() File "/dgsm-docker/servers.py", line 18, in refresh servers = self.get() File "/dgsm-docker/servers.py", line 49, in get return json.loads(data) File "/usr/local/lib/python3.10/json/**init**.py", line 346, in loads return _default_decoder.decode(s) File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode obj, end = self.scan_once(s, idx) json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 9 column 5 (char 234) Server Config found! Settings Config found! usermod: no changes usermod: no changes Server Config found! Settings Config found!
> 
> a find on the bot.py file produced several locations. I ended up making the change on all the following: /var/lib/docker/btrfs/subvolumes/1784ad43d48d350fba43a1e3422a6da072e29c367c61b5ee46811ab459b31c3b/dgsm-docker/bot.py /var/lib/docker/btrfs/subvolumes/321a826569eed6449722cd515846c3ff9b7862c64829f8bdb1907d7d5a361345/dgsm-docker/bot.py /var/lib/docker/btrfs/subvolumes/4bebe5b47999f96791d7b43fe442df77ff83ecd9b8cf8abc38b7d2f5e9fbecfd-init/dgsm-docker/bot.py /var/lib/docker/btrfs/subvolumes/4bebe5b47999f96791d7b43fe442df77ff83ecd9b8cf8abc38b7d2f5e9fbecfd/dgsm-docker/bot.py /var/lib/docker/btrfs/subvolumes/5ca820afe73afdb97125117ba4f1c8764ef2c02a236d956dd5d6851836831d3d/dgsm-docker/bot.py

Bot needs to be updated. What version of discord py are you running?

**Comment by jadewolf05** [comment]
I'm not sure what version of discord.py it is.  its using the latest version of discordGSM from the unraid community apps.

**Comment by jadewolf05** [comment]
I took a look inside one of the discord.py files and they don't show any version info.

**Comment by xLeviNx** [comment]
I mean that discordgsm needs to be updated. And unraid community apps?

**Comment by jadewolf05** [comment]
> I mean that discordgsm needs to be updated. And unraid community apps?

https://unraid.net/community/apps?q=Discord-GameServerMonitor#r

**Comment by xLeviNx** [comment]
https://github.com/DiscordGSM/GameServerMonitor

Use this
