### ISSUE TITLE
Bot cannot run, "intents" error

### ISSUE THREAD

**Issue by AWL-Gaming** [BattlefieldDuck/DiscordGSM#32]
Trying to run the bot on both Windows Server and Ubuntu 20.04 and after fulfilling all requirements, the same error shows up regardless of the OS.

**Linux**
![image](https://user-images.githubusercontent.com/22678541/185819094-6f67b480-84da-4d73-8aa6-b879e5bd9506.png)

```
discordgsm@WIN-32TD5U1EI7P:~/DiscordGSM$ python3 bot.py
Traceback (most recent call last):
  File "bot.py", line 363, in <module>
    client = commands.Bot(command_prefix=PREFIX)
TypeError: __init__() missing 1 required keyword-only argument: 'intents'
```

**Windows**
![image](https://user-images.githubusercontent.com/22678541/185819147-4b2d8869-d980-44ba-afa9-49d1c6da6cde.png)

```
PS F:\DGSM> python bot.py
Traceback (most recent call last):
  File "F:\DGSM\bot.py", line 363, in <module>
    client = commands.Bot(command_prefix=PREFIX)
TypeError: __init__() missing 1 required keyword-only argument: 'intents'
```

**Comment by AWL-Gaming** [comment]
**Update:** Adding the following lines fixed the issue:
```
intents = discord.Intents.default() # or .all() if you ticked all, that is easier
intents.members = True # If you ticked the SERVER MEMBERS INTENT
client = commands.Bot(command_prefix=PREFIX, intents=intents)
```
But now another issue is present:
```
PS F:\DGSM> python bot.py
2022-08-22 02:55:01: Starting DiscordGSM v.1.9.3
Traceback (most recent call last):
  File "F:\DGSM\bot.py", line 456, in <module>
    discordgsm.start()
  File "F:\DGSM\bot.py", line 70, in start
    self.update_messages.start()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\tasks\__init__.py", line 398, in start
    self._task = asyncio.create_task(self._loop(*args, **kwargs))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 360, in create_task
    loop = events.get_running_loop()
RuntimeError: no running event loop
sys:1: RuntimeWarning: coroutine 'Loop._loop' was never awaited
```

**Comment by kferrano** [comment]
Remove your edits in bot.py
Use `py -m pip uninstall  discord.py` and uninstall Discord.py 2.0.1
and then install the discord.py 1.7.3 with: `py -3 -m pip install -U  discord.py==1.7.3`

**Comment by xLeviNx** [comment]
https://github.com/DiscordGSM/GameServerMonitor

Use this. Wouldn't recommend using an outdated bot that Discord will end up scraping when its not updated to their new standards

**Comment by PABessero** [comment]
In case you still prefer this bot over GSM (the new version) my new PR fixes the bot to work with discord.py 2.0.1
